modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="prophecy_stick"
version="1.0.0"
displayName="Prophecy Stick"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Gunter Wambaugh"
description='''
Ore finder.
'''

[[dependencies.prophecy_stick]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




